config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'
  resources :users do
    resources :items, only: [:new, :create]
  end
  resources :items, only: [:show] do
   resources :exchanges, only: [:create ]
  end
  resources :exchanges, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  belongs_to :item
  # has_one :lender, through: :item, source: :user

  validates :user, :item, :start_date, :end_date, presence: true
  validates :user, uniqueness: { scope: :item }

  validate :start_date_cannot_be_in_the_past, :end_date_cannot_be_before_start_date
  validate :user_cannot_borrow_from_self

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_cannot_be_before_start_date
    if end_date.present? && start_date.present? && end_date < start_date
      errors.add(:end_date, "can't be before Start date")
    end
  end

  def user_cannot_borrow_from_self
    if user == item.user
      errors.add(:user, "cannot borrow from himself or herself")
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :exchange
  mount_uploader :photo, PhotoUploader
  validates :token_value, :name, :photo, presence: true

  include PgSearch
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :photo, PhotoUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  geocoded_by :location
  has_many :exchanges, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :lender_exchanges, through: :items, source: :exchange
  validates :username, presence: true, uniqueness: true
  validates :location, presence: true
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :location, :photo])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :location, :photo])
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: [:show]

  def index
    @borrower_exchanges = Exchange.where(user_id: current_user)
    @lender_exchanges = current_user.lender_exchanges
    @available_items = current_user.items.select {|item| item.exchange.nil?}
  end

  def create
    @item = Item.find(params[:item_id])
    @exchange = Exchange.new(exchange_params)
    @exchange.item = @item
    @exchange.user = current_user
    if @exchange.save
      redirect_to exchange_path(@exchange)
    else
      render 'items/show'
    end
  end

  def show
    @item = @exchange.item
  end

  private

  def exchange_params
    params.require(:exchange).permit(:start_date, :end_date)
  end

  def set_exchange
    @exchange = Exchange.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_item, only: [:show, :destroy]

  def index
    if user_signed_in?
      # current_user.to_coordinates => [current_user.latitude, current_user.longitude]
      users_near = User.near(current_user.to_coordinates, 50).map { |user| user.username }

      # paginate_settings => :page => params[:page], :per_page => 12

      @items = Item.joins(:user).where('users.username IN (?)', users_near).paginate(page: params[:page], per_page: 8)

      if params[:query].present?
        items_near_current_user = Item.joins(:user).where('users.username IN (?)', users_near)
        items_ncu_filtered = items_near_current_user.search_by_name_and_description(params[:query])
        @items = items_ncu_filtered.paginate(page: params[:page], per_page: 8)
      end
    else
      users_near = User.near('Tokyo, Japan', 100).map { |user| user.username }
      # @items = Item.all.paginate(page: params[:page], per_page: 12)
      @items = Item.joins(:user).where('users.username IN (?)', users_near).paginate(page: params[:page], per_page: 8)
      if params[:query].present?
        items_anonymous_filtered = Item.search_by_name_and_description(params[:query])
        @items = items_anonymous_filtered.paginate(page: params[:page], per_page: 8)
      end
    end


    @markers = @items.map do |item|
      {
        lat: item.user.latitude,
        lng: item.user.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to item_path(@item)
    else
      render 'items/new'
    end
  end

  def show
    @exchange = Exchange.new
    @markers = [@item].map do |item|
      {
        lat: item.user.latitude,
        lng: item.user.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:id, :name, :description, :token_value, :photo, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    redirect_to root_path
  end

  private
  
  def user_params
    params.require(:user).permit(:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exchanges/index.html.erb
<div class="container">
  <h1>My Dashboard</h1>

  <h3>Currently Borrowing</h3>
    <% @borrower_exchanges.each do |borrower_exchange| %>
      <div class="message">
        <%= cl_image_tag(borrower_exchange.item.user.photo, class: "user_avatar") %>
        <div class="message-name">
          <h3><%= borrower_exchange.item.user.username %></h3>
        </div>
        <div class="message-body">
          <p><strong><%= link_to borrower_exchange.item.name, exchange_path(borrower_exchange) %></strong></p>
          <p>
            <%= borrower_exchange.item.description %>
          </p>
        </div>
        <div class="message-status">
          <p class="status pending">Token</p>
          <p class="price"><%= borrower_exchange.item.token_value %></p>
        </div>
      </div>
    <% end %>

  <h3>Currently Lending</h3>
  <ul>
    <% @lender_exchanges.each do |lender_exchange| %>
      <div class="message">
        <%= cl_image_tag(borrower_exchange.user.photo, class: "user_avatar") %>
        <div class="message-name">
          <h3><%= borrower_exchange.user.username %></h3>
        </div>
        <div class="message-body">
          <p><strong><%= link_to lender_exchange.item.name, exchange_path(lender_exchange) %>
       | borrower: <%= lender_exchange.user.username %></strong></p>
          <p>
            <%= lender_exchange.item.description %>
          </p>
        </div>
        <div class="message-status">
          <p class="status pending">Token</p>
          <p class="price"><%= lender_exchange.item.token_value %></p>
        </div>
      </div>
    <% end %>
  </ul>

  <h3>Available to Lend</h3>
  <% @available_items.each do |available_item| %>
    <div class="message">
        <%= cl_image_tag(available_item.photo, class: "item_photo") %>
          <div class="message-body">
            <p><strong><%= link_to available_item.name, exchange_path(available_item) %></strong></p>
          <p>
            <%= available_item.description %>
          </p>
          </div>
          <div class="message-status">
            <p class="status pending">Token</p>
            <p class="price"><%= available_item.token_value %></p>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/exchanges/show.html.erb
<div class="main-block" style="padding: 0px 25px 5px 25px; margin: 40px auto; box-shadow: 1px 2px 3px rgba(0,0,0,0.8);">
  <h1 style="padding-top: 20px;">Request Confirmed!</h1>
  <h4 style="text-align: center; padding-bottom: 25px;"><strong><%= @exchange.start_date.strftime('%A, %b %d, %Y')  %><small> to </small> <%= @exchange.end_date.strftime('%A, %b %d, %Y') %></strong></h4>
  <div class="item-description">
    <div class="item-info">
      <div class="item-name pl-2" style="padding-left: 35px;">
        <h3> <%= @item.name %></h3>
      </div>
      <div class="lender-name" style="padding-left: 35px;">
        <div class="lender-avatar">
          <p> <%= @item.description %></p>
        </div>
      </div>
    </div>
    <div class="item-image" style="margin: 0px 35px 10px 0px; box-shadow: 1px 2px 3px rgba(0,0,0,0.8);">
      <img src="<%= @item.photo %>">
    </div>
  </div>
  <div class="borrowing-period">
    <h4></h4>
  </div>
  <div class="pickup-location" style="padding-top: 10px;" >
    <div class="location-address" style="text-align: center; padding-top: 15px;">
      <h3>Pickup Location</h3>
      <h4 style="padding: 35px 0px 35px 0px;"><strong><%= @item.user.location.capitalize %></strong></h4>
      <p style="text-align: center; font-style: italic;">Please contact user <strong><%= @item.user.username %></strong> to arrange the time and exact location.</p>
    </div>
    <div class="location-map" style="margin-left: 20px; box-shadow: 1px 2px 3px rgba(0,0,0,0.8);">
      <img src="https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&sensor=true&maptype=roadmap&markers=color:red|<%= "#{@item.user.location + "+station&key=#{ENV['GOOGLE_API_BROWSER_KEY']}"}"%>" alt="Location Map">
      <%#= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&sensor=false&maptype=roadmap&markers=color:red|#{@item.user.location}"%>
    </div>
  </div>
  <div class="home-button" style="padding-top: 10px;">
  <%= link_to "home", root_path, class: "btn" %>
  </div>
</div>

app/views/items/_form.html.erb
<%= simple_form_for([current_user, @item]) do |f| %>
  <% if @item.errors.any? %>
    <div class="errors" id="error_explanation">
      <h2 class="error-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li class="error"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="container">
    <div class="form-container">
      <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
          <%= f.label :"Add new item" %>
          <br>
          <%= f.text_field :name, placeholder:"ex. chainsaw"  %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-offset-3 col-sm-6" id="description">
          <%= f.label :"Add a short description" %>
          <br>
          <%= f.text_area :description, placeholder:"ex. an old but good chainsaw that cuts well", style: "width: 100%; height: 200px"  %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
          <%= f.label :token_value %>
          <br>
          <%= f.text_field :token_value %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
          <%= f.input :photo, input_html: { class: "btn" } %>
          <%= f.input :photo_cache, as: :hidden %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-offset-5 col-sm-6">
        <%= f.submit "Submit", class: "btn" %>
      </div>
    </div>
  </div>

<% end %>

app/views/items/_map.html.erb
<div
  id="map"
  style="width: 100%;"
  data-markers="<%= markers.to_json %>"
></div>

app/views/items/index.html.erb
<div class="main-container">
  <div class="cards-container">
    <div class="container">
      <div class="row">
        <% @items.each do |item| %>
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <%= link_to item_path(item), class: "center-align" do%>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= item.photo %>');">

                <%= cl_image_tag(item.user.photo, :width =>30, :height => 30, :crop => :thumb, :gravity => :face, class: "card-user") %>
                  <p class="card-item-username"><%= item.user.username %> </p>

                <div class="card-description">
                  <%= item.name.capitalize %>
                </div>
                <div class="item-location">
                  <p>
                    <%= item.user.location.capitalize %>
                    <br>
                    <%= item.user.distance_to(current_user).round(2).to_s + "km away" if user_signed_in? %></p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <%= will_paginate @items, class: "digg_pagination mt-2 mx-auto"%>
    </div>
  </div>

  <%= render "items/map", markers: @markers %>

</div>

app/views/items/new.html.erb
<%= render 'form', item: @item %>

app/views/items/show.html.erb
<div class="container">
  <div class="item-container">
    <div class="item-details">
      <div class="item-user-details">
        <div class="item-details-name">
          <h4 class="center-align"><%= @item.name %></h4>
        </div>
        <div class="item-details-user">
          <div class="username">
            <h6><%= @item.user.username %></h6>
          </div>
          <div class="user-avatar">
            <%= cl_image_tag(@item.user.photo) %>
          </div>
        </div>
      </div>
      <div class="item-details-desc">
        <p><%= @item.description %></p>
      </div>
      <% if @exchange.errors.any? %>
        <div class="errors">
          <h2 class="error-title"><%= pluralize(@exchange.errors.count, "error") %> prohibited this item from being saved:</h2>
          <% @exchange.errors.full_messages.each do |error| %>
            <p class="error"><%= error %></p>
          <% end %>
        </div>
      <% end %>

    </div>

    <div class="item-request">
      <div class="item-request-photo">
        <%= cl_image_tag @item.photo, class: "item-request-photo" %>
      </div>
      <div class="item-request-form">
        <%= simple_form_for [@item, @exchange] do |f| %>
          <%= f.error :start_date, id: 'start_date_error' %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.error :end_date, id: 'end_date_error' %>
          <%= f.input :end_date, as: :date, html5: true %>
          <%= f.submit "Request to borrow", class: "btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_dropdown.html.erb
<li>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer page-footer blue-grey darken-4">
  <div class="container container-footer">
    <div class="row">
      <div class="col-xs-4 navbar-wagon-link">About us</div>
      <div class="col-xs-4 navbar-wagon-link">Privacy Policy</div>
      <div class="col-xs-4 navbar-wagon-link">&copy; Toolio, 2018</div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <%= link_to root_path do %>
    <%= image_tag "logo.png", class: "logo"%>
  <% end %>

  <form class="form-inline" id="search-bar">
    <input class="form-control mr-sm-2" name="query" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" formmethod:"get" formaction="/">Search</button>
  </form>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <%= link_to "Add new item", new_user_item_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Dashboard", exchanges_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>

    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>


    <!-- Profile picture with dropdown list -->
    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag(current_user.photo, :width =>85, :height => 85, :crop => :thumb, :gravity => :face, data: {toggle: "dropdown"}) %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <%= render "layouts/dropdown" %>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- TODO: Unsigned in User Icon -->
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg collapsed-menu-gray">
    <div class="dropdown">
      <% if user_signed_in? %>
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <%= render "layouts/dropdown" %>
        </ul>
      <% else %>
        <!-- TODO: MOBILE Unsigned in User Icon -->
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tu-Tu-Toolio</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="main-content"><%= render 'layouts/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>

    </div>
    <div class="footer"><%= render 'layouts/footer' %></div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>